"use client";

import './styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/header';
import { ThemeUIProvider } from 'theme-ui';
import theme from './styles/theme/theme';

const inter = Inter({ subsets: ['latin'] })

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeUIProvider theme={theme}>
      <Header />

      <body className={inter.className}>{children}</body>
      </ThemeUIProvider>
    </html>
  )
}
