import * as React from 'react';
import type { Metadata } from 'next'
import Header from './header';
import Container from '@mui/material/Container';
import Footer from './footer';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children, allPostHeaders, home
}: {
  children: React.ReactNode,
  allPostHeaders: any,
  home: any
}) {
  return (
      <Container maxWidth="lg">
          <Header />
          {children}
          <Footer allPostsHeaders={allPostHeaders}/>
        </Container>
  )
}
