import * as React from 'react';
import type { Metadata } from 'next'
import Header from './header';
import ThemeRegistry from '../pages/theme-registry';
import Container from '@mui/material/Container';

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function Layout({
  children, home
}: {
  children: React.ReactNode,
  home: any
}) {
  return (
      <Container maxWidth="lg">
        <ThemeRegistry options={{ key: 'mui' }}>
          <Header />
          {children}
        </ThemeRegistry>
        </Container>
  )
}
